roles: []
color_scheme:
  colors:
  - {name: Dark Theme - Background, color: '#131313'}
  - {name: Dark Theme - Button background, color: '#333333'}
  - {name: Dark Theme - Foreground, color: '#ffffff'}
  - {name: Dark Theme - Selected Button background, color: '#8f8f8f'}
  preset_groups: []
